/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.91
 * Generated at: 2024-07-22 04:27:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1721028140268L));
    _jspx_dependants.put("jar:file:/D:/javaee/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BankApplication-mvc/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1323238578000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.2/css/all.css\">\r\n");
      out.write("<style>\r\n");
      out.write("/* Importing fonts from Google */\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap');\r\n");
      out.write("\r\n");
      out.write("/* Resetting */\r\n");
      out.write("* {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    font-family: 'Poppins', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    background: #ecf0f3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper {\r\n");
      out.write("    max-width: 350px;\r\n");
      out.write("    min-height: 550px;\r\n");
      out.write("    margin: 80px auto;\r\n");
      out.write("    padding: 40px 30px 30px 30px;\r\n");
      out.write("    background-color: #ecf0f3;\r\n");
      out.write("    border-radius: 15px;\r\n");
      out.write("    box-shadow: 13px 13px 20px #cbced1, -13px -13px 20px #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo {\r\n");
      out.write("    width: 100px; /* Adjusted size */\r\n");
      out.write("    margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo img {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100px; /* Adjusted size */\r\n");
      out.write("    object-fit: cover;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    box-shadow: 0px 0px 3px #5f5f5f,\r\n");
      out.write("        0px 0px 0px 5px #ecf0f3,\r\n");
      out.write("        8px 8px 15px #a7aaa7,\r\n");
      out.write("        -8px -8px 15px #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper .name {\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    font-size: 1.4rem;\r\n");
      out.write("    letter-spacing: 1.3px;\r\n");
      out.write("    padding-left: 10px;\r\n");
      out.write("    color: #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper .form-field input, .wrapper .form-field select {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    display: block;\r\n");
      out.write("    border: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    background: none;\r\n");
      out.write("    font-size: 1.2rem;\r\n");
      out.write("    color: #666;\r\n");
      out.write("    padding: 10px 15px 10px 10px;\r\n");
      out.write("    /* border: 1px solid red; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper .form-field {\r\n");
      out.write("    padding-left: 10px;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("    border-radius: 20px;\r\n");
      out.write("    box-shadow: inset 8px 8px 8px #cbced1, inset -8px -8px 8px #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper .form-field .fas, .wrapper .form-field .far {\r\n");
      out.write("    color: #555;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper .btn {\r\n");
      out.write("    box-shadow: none;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    background-color: #03A9F4;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    border-radius: 25px;\r\n");
      out.write("    box-shadow: 3px 3px 3px #b1b1b1,\r\n");
      out.write("        -3px -3px 3px #fff;\r\n");
      out.write("    letter-spacing: 1.3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper .btn:hover {\r\n");
      out.write("    background-color: #039BE5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-size: 0.8rem;\r\n");
      out.write("    color: #03A9F4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper a:hover {\r\n");
      out.write("    color: #039BE5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media(max-width: 380px) {\r\n");
      out.write("    .wrapper {\r\n");
      out.write("        margin: 30px 20px;\r\n");
      out.write("        padding: 40px 15px 15px 15px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("        <img src=\"C:/Users/hp/OneDrive/Desktop/logo1.png\">   \r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"text-center mt-4 name\">\r\n");
      out.write("        Bank Name\r\n");
      out.write("    </div>\r\n");
      out.write("    <form action=\"BankController\" method=\"post\" class=\"p-3 mt-3\">\r\n");
      out.write("        <input type=\"hidden\" name=\"action\" value=\"login\">\r\n");
      out.write("        <div class=\"form-field d-flex align-items-center\">\r\n");
      out.write("            <span class=\"far fa-user\"></span>\r\n");
      out.write("            <input type=\"text\" name=\"email\" id=\"email\" placeholder=\"Email\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-field d-flex align-items-center\">\r\n");
      out.write("            <span class=\"fas fa-key\"></span>\r\n");
      out.write("            <input type=\"password\" name=\"password\" id=\"password\" placeholder=\"Password\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"form-field d-flex align-items-center\">\r\n");
      out.write("            <span class=\"fas fa-user-tag\"></span>\r\n");
      out.write("            <select name=\"role\" id=\"role\" required>\r\n");
      out.write("                <option value=\"\" disabled selected>Select Role</option>\r\n");
      out.write("                <option value=\"admin\">Admin</option>\r\n");
      out.write("                <option value=\"customer\">Customer</option>\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button class=\"btn mt-3\" type=\"submit\">Login</button>\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("    <div class=\"text-center fs-6\">\r\n");
      out.write("        <a href=\"#\">Forget password?</a> or <a href=\"#\">Sign up</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /login.jsp(145,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty errorMessage}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            <p class=\"text-danger text-center mt-3\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
